### PR TITLE
Fixes #77 create movie cards 

### LINKED ISSUE #77: Create movie cards
**Task:**

- [ ] Make a function, that takes a movie object from json file as parameter, creates an <article>with an image, title and a booking button based on the specifc movie object. It should then return the article.

### PR DESCRIPTION
**Pull request by marcusmoller97**
**Object that contains functionallity to:**
* create movieCard (made as an article) with
    * movie container, classname: **movieWrapper**
    * Movie container contains:
        * img
        * h2
        * button with text and icon
* Function to create movie cards from all elements in an array. (the array needs to follow the movies.json syntax)

**In this pull request I added movie card to index.html from an example array for reference and to easier style the card later. The element is figure.movie.

### CODE REVIEW

**Review by EmpyreanMist — APPROVED** [review]
Great work! Code is easy to understand :)

**Comment by marcusmoller97** [comment]
Don't approve this just yet. Minor fixes needs to be done.

**Review by kikoDevv — APPROVED** [review]
Nicely done! although there is some console error in the code but im not sure if its for everyone.

**Review by jan-elia-24 — APPROVED** [review]
Nicely deone!

**Pull request merged**
