### PR TITLE
Exit modal#61

### PR DESCRIPTION
**Pull request by EmpyreanMist**
X button that allows you to close the modal.

image

### CODE REVIEW

**Review by kai-ericson — APPROVED** [review]
Good job! The code is easy to understand and the exit button works as it should

**Review by NordicNomadicLife — APPROVED** [review]
looks good

**Review by itsJoel59 — APPROVED** [review]
Looks good both visually in UI and code! Looks like PR has merge conflicts tho.

**Review by marcusmoller97 — APPROVED** [review]
Everything in the js code looks good and your sass code also looks okay. There seems to be a minor merge conflict with the footer style in the css code let's fix it and then I think we can merge this. Good job! 😄

**Pull request merged**
