### PR TITLE
81 read all movies from json file

### PR DESCRIPTION
**Pull request by itsJoel59**
I added an object with 3 functions that fetches movie data from movies.json and adds it to an array in the object:

1. Gives all movies
2. Gives released movies
3. Gives upcoming movies

Here is an example of the first function:
image

I also imported this object as a module.

**Note:** I believe that these functions should be used within the functions that create the cards, and that function needs to be async as well in order to work.

### CODE REVIEW

**Review by marcusmoller97 — APPROVED** [review]
Nice work I have checked everything and I see that we get the data as global arrays that can be used from main.js. As an initial step I think this is fine. 
Keep up the good work! 👍

**Review by kikoDevv — APPROVED** [review]
This should do the trick for now, Thanks for the file!

**Review by EmpyreanMist — APPROVED** [review]
Well done!

**Comment by EmpyreanMist** [comment]
I'll merge :)

**Pull request merged**
