### PR TITLE
Style for show all movie pages

### PR DESCRIPTION
**Pull request by kikoDevv**
The page is styled with smooth animation, scroll time line and simple to use Ui. 
Styling include for the following elements.
- [x] header.
- [x] Highlighted section 
- [x] filtermenu.
- [x] main.
- [x]  footer.
- [x]  page is linked in navBar.
Additional styling has been added to the page not requested from the BPI but for studie purpose.
Screenshot 2024-12-27 at 13 38 46
Screenshot 2024-12-27 at 13 20 27

### CODE REVIEW

**Comment by kikoDevv** [comment]
Patched the merge conflict.

**Review by jan-elia-24 — APPROVED** [review]
Nice job! Proffs level

**Review by NordicNomadicLife — APPROVED** [review]
Looks good i like the animation

**Review by EmpyreanMist — APPROVED** [review]
Visually stunning! Merging to main :)

**Pull request merged**
