### PR TITLE
17 json file to store movie data

### PR DESCRIPTION
**Pull request by itsJoel59**
Created a json file for containing movies data. The json provides an object that contains an array with each movie as a unique object. It currently contains 10 movies.
image

### CODE REVIEW

**Review by NordicNomadicLife — APPROVED** [review]
looks good, Good job

**Comment by marcusmoller97** [comment]
Good job!

**Review by marcusmoller97 — APPROVED** [review]
Looks good!

**Review by kikoDevv — APPROVED** [review]
Nicely done adding all the necessary details about the movie.

**Pull request merged**
